name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [26, 24, 22]

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Packages
        run: npm ci

      - name: Typecheck
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage/lcov.info
          flag-name: node:${{ matrix.node }}
          parallel: true

  coverage-aggregation:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
